'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CraftBand.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  新たに&apos;{0}&apos;を追加します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AskConfirmAdd() As String
            Get
                Return ResourceManager.GetString("AskConfirmAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  既存の&apos;{0}&apos;に{1}を追加します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AskConfirmAppend() As String
            Get
                Return ResourceManager.GetString("AskConfirmAppend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  『設定時の寸法単位』を変更しても、既に設定済みの値は変わりません。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AskConfirmChangeUnit() As String
            Get
                Return ResourceManager.GetString("AskConfirmChangeUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &apos;{0}&apos;をすべて削除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AskConfirmDeleteGroup() As String
            Get
                Return ResourceManager.GetString("AskConfirmDeleteGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &apos;{0}&apos;(ひも番号{1})を削除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AskConfirmDeleteSub() As String
            Get
                Return ResourceManager.GetString("AskConfirmDeleteSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}が変更されました。選択されたファイルを読み直しますか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AskReloadMasterDataFile() As String
            Get
                Return ResourceManager.GetString("AskReloadMasterDataFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0} 本 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CalcOutCount() As String
            Get
                Return ResourceManager.GetString("CalcOutCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  カットリスト に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CalcOutCutList() As String
            Get
                Return ResourceManager.GetString("CalcOutCutList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}幅 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CalcOutLane() As String
            Get
                Return ResourceManager.GetString("CalcOutLane", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  最長 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CalcOutLonguest() As String
            Get
                Return ResourceManager.GetString("CalcOutLonguest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  面積長 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CalcOutShortest() As String
            Get
                Return ResourceManager.GetString("CalcOutShortest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  集計値 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CalcOutSum() As String
            Get
                Return ResourceManager.GetString("CalcOutSum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  レコードを追加できませんでした。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrAddRecord() As String
            Get
                Return ResourceManager.GetString("ErrAddRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}行目{1}値のデータエラー{2}{3} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrGridData() As String
            Get
                Return ResourceManager.GetString("ErrGridData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}行目{1}値には{2}以上の数値を設定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrGridMinimumValue() As String
            Get
                Return ResourceManager.GetString("ErrGridMinimumValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  設定データを保存するファイルが指定されませんでした。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrMasterTableFileCancel() As String
            Get
                Return ResourceManager.GetString("ErrMasterTableFileCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  起動に必要なパラメータがありません。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrNoInitializeParameters() As String
            Get
                Return ResourceManager.GetString("ErrNoInitializeParameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  新しい/既存の{0}を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrNoName() As String
            Get
                Return ResourceManager.GetString("ErrNoName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  指定ファイル&apos;{0}&apos;から設定データを読み取ることができませんでした。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrReadMasterTableFile() As String
            Get
                Return ResourceManager.GetString("ErrReadMasterTableFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  設定データのファイル&apos;{0}への保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrSaveMasterTableFile() As String
            Get
                Return ResourceManager.GetString("ErrSaveMasterTableFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  未定義のDataType に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LOG_DataType() As String
            Get
                Return ResourceManager.GetString("LOG_DataType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  例外発生 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LOG_Exception() As String
            Get
                Return ResourceManager.GetString("LOG_Exception", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  未定義のフィールド名 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LOG_FieldName() As String
            Get
                Return ResourceManager.GetString("LOG_FieldName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  後処理完了 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LOG_Finalized() As String
            Get
                Return ResourceManager.GetString("LOG_Finalized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ダイアログ表示終了 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LOG_FormEnd() As String
            Get
                Return ResourceManager.GetString("LOG_FormEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  指定されたファイル&apos;{0}&apos;は読み取れませんでした。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property WarningBadWorkData() As String
            Get
                Return ResourceManager.GetString("WarningBadWorkData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  指定されたファイル&apos;{0}&apos;への保存ができませんでした。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property WarningFileSaveError() As String
            Get
                Return ResourceManager.GetString("WarningFileSaveError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイル&apos;{0}&apos;を起動できませんでした。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property WarningFileStartError() As String
            Get
                Return ResourceManager.GetString("WarningFileStartError", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
