'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CbMesh.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  ファイル&apos;{0}&apos;があるため、拡張子を変更できません。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MsgCantChange() As String
            Get
                Return ResourceManager.GetString("MsgCantChange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &apos;{0}&apos;に変更しました。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MsgChanged() As String
            Get
                Return ResourceManager.GetString("MsgChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &apos;{0}&apos;に変更できません -{1} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MsgChangeError() As String
            Get
                Return ResourceManager.GetString("MsgChangeError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}({1})を起動できませんでした。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MsgCouldNotStartExe() As String
            Get
                Return ResourceManager.GetString("MsgCouldNotStartExe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}のデータファイルです。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MsgDataFile() As String
            Get
                Return ResourceManager.GetString("MsgDataFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &apos;{0}&apos; {1}本幅 ({2} , {3} , {4}) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MsgInfo1() As String
            Get
                Return ResourceManager.GetString("MsgInfo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タイトル【{0}】{1} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MsgInfo2() As String
            Get
                Return ResourceManager.GetString("MsgInfo2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  [ファイル]メニューから[開く]もしくはドラッグ＆ドロップでファイルを指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MsgNeedFile() As String
            Get
                Return ResourceManager.GetString("MsgNeedFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  拡張子の変更は不要です。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MsgNoNeedChange() As String
            Get
                Return ResourceManager.GetString("MsgNoNeedChange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  シリーズの設定ファイルです。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MsgSettingFile() As String
            Get
                Return ResourceManager.GetString("MsgSettingFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  起動可能なデータファイル: に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MsgStartable() As String
            Get
                Return ResourceManager.GetString("MsgStartable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}({1})を起動しました。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MsgStartExe() As String
            Get
                Return ResourceManager.GetString("MsgStartExe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  DLLエラー に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TitleDllError() As String
            Get
                Return ResourceManager.GetString("TitleDllError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  例外発生 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TitleException() As String
            Get
                Return ResourceManager.GetString("TitleException", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
